name: build infrastructure

on:
  push:

jobs:
  terraform:
    name: terraform apply
    runs-on: ubuntu-latest
    env:
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: terraform setup
      uses: hashicorp/setup-terraform@v1
    
    - name: terraform initialization
      run: terraform init
    
    - name: terraform format check
      run: terraform fmt -check
    
    - name: terrafrom validation
      run: terraform validate
    
    - name: checkov terraform checks
      id: checkov
      uses: bridgecrewio/checkov-action@master
      with:
        directory: '.'
        framework: terraform
        output_format: json
        download_external_modules: true
        log_level: DEBUG

    - name: terraform plan
      run: terraform plan
    
    - name: terraform apply
      run: terraform apply -auto-approve

