name: build infrastructure

on:
  push:

jobs:
  terraform:
    name: build infrastructure
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}

    defaults:
      run:
        shell: bash
    
    steps:
    - name: checkout repository
      uses: actions/checkout@v2
    
    - name: terraform setup
      uses: hashicorp/setup-terraform@v1
    
    - name: terraform initialization
      run: terraform init
      working-directory: ./terraform
    
    - name: terraform format check
      run: terraform fmt -check
      working-directory: ./terraform
    
    - name: terrafrom validation
      run: terraform validate
      working-directory: ./terraform
    
    # - name: checkov terraform checks
    #   id: checkov
    #   uses: bridgecrewio/checkov-action@master
    #   with:
    #     directory: '.'
    #     framework: terraform
    #     output_format: json
    #     download_external_modules: true
    #     log_level: DEBUG

    # - name: terraform plan
    #   run: terraform plan
    
    # - name: terraform apply
    #   run: terraform apply -auto-approve


